name: Build and Deploy Hugo
on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    name: Deploy Hugo Website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install Hugo with deploy support
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
        CGO_ENABLED=1 go install -tags extended,withdeploy github.com/gohugoio/hugo@v0.138.0
        
    - name: Build site
      run: hugo
      
    - name: Deploy to S3
      run: hugo deploy --force --maxDeletes -1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_ACCESS_KEY }}
