name: Scaleway builder/deployer

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    name: Deploy Hugo Website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: setup hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: '0.138.0'
    - name: build site
      run: hugo
    - name: deploy to scaleway
      run: hugo deploy --force --maxDeletes -1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_ACCESS_KEY }}
